### ISSUE TITLE
Sporadic ECONNRESET that breaks connection in nearlib

### ISSUE THREAD

**Issue by nearmax** [near/near-api-js#328] opened 2020-05-22 00:10 UTC
When using nearlib in a long running node.js app the connection is sometimes getting randomly dropped and the entire app crashes with ECONNRESET error. This is a blocker for the bridge since bridge relayers are long running node.js services that should not crash.

This error is not easy to reproduce since it is random and does not seem to depend on the code that uses nearlib.

**Comment by frol** [comment] 2020-05-22 02:26
During load testing, @ailisp discovered that there is a hard limit on Node.js that does not allow more than 200 parallel connections to a single host (if I recall it correctly). Thus, it was not a bug of near-api-js. Are you sure that you don't hit this same limit?

**Comment by nearmax** [comment] 2020-05-22 15:25
I have only one or maybe two connections open to a single host, unless nearlib opens them for me.

**Comment by ailisp** [comment] 2020-05-22 17:49
Your described ECONNRESET is probably due to occasional network disconnect/packet loss. It is possible to catch/retry to recover from ECONNRESET error, e.g. i was able to run near-ops/loadtest.js with a lot of ECONNRESET for a week but not crash

**Comment by frol** [comment] 2020-05-22 20:34
Well, even if we would not encounter those errors, you should handle such errors and retry. Unless this happens like tens of times reproducibly, there is nothing wrong with it. Otherwise, we need to debug the network, there is nothing on near-api-js side, it is a simple wrapper around `fetch` API.

@nearmax I am going to close it. Feel free to reopen it if you feel that there is still an action item here.

**Comment by nearmax** [comment] 2020-05-22 20:40
@ailisp This happens consistently with the local node, like a dozen times a day, as I am working with the local node using near-api-js.

@frol It sounds like it is within the scope of near-api-js responsibility to do those retries. The action item would be to implement such functionality. Reopening this issue. (Thank you for closing though! I think we should not hesitate to close the issues)

**Comment by ailisp** [comment] 2020-05-22 21:53
On local test to a local node I had encounter ECONNRESET too. It seem to happen due to neard has some error. I agree with @nearmax this should be handled in nearlib, ideally it should not expose any low level error like this, but nearlib defined error classes.

**Comment by nearmax** [comment] 2020-05-22 22:38
Assigning it to @frol since it is relevant to RPC and it creates problems for the bridge which are both in the Middleware scope.

**Comment by volovyk-s** [comment] 2021-02-23 15:30
@nearmax @frol is it still relevant? Is it still a problem for the bridge?

**Comment by frol** [comment] 2021-02-23 20:04
I haven't heard about it since then. I believe it was a load-balancer configuration issue or something with infrastructure which we never identified.

**Comment by volovyk-s** [comment] 2021-02-24 09:25
Ok, then I will close it. @nearmax feel free to open it if we will face this issue again.

**Closed by volovyk-s** 2021-02-24 09:25 UTC
Labels: P1, bug
