### ISSUE TITLE
Send multiple TXs to Wallet to be signed

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-api-js#356] opened 2020-07-06 18:48 UTC
There are in many cases need to send a massive number of transactions. 

The current API of an Account is limited to single access key which means that needs to wait for transaction to process to avoid nonce collision.

First change would be to adjust `Signer` to also optionally take `public_key` and support multiple keys per account id.
 Add a way to retrieve list of public keys for a given account id.

The second is support batch actions, e.g.
 ```
 account.batch(<span class="error">[...]</span>.map(() => 

 { account.prepareFunctionCall(...) } 

));
 ```

or something, where it accumulates prepared transactions, signs them with available public key and sends them.

**Comment by vgrichina** [comment] 2020-07-06 19:06
As for `Signer` I think what we can do is just rename `networkId` into generic `namespace`. As it's not really used in any specific manner besides creating another namespace for keys (and so having multiple keys for given account0.

However I think that generally it makes sense to start with just a demo script of submitting batch transactions and then move stuff to near-api-js as necessary. 

> where it accumulates prepared transactions, signs them with available public key and sends them.

won't they need to be signed with different public keys to actually allow submitting a lot of them at the same time? Or I misunderstand something?

**Comment by potatodepaulo** [comment] 2020-07-14 18:39
@janedegtiareva pointed this out that this is especially important for users with virtual accounts, which we are encouraging before Phase 2.

**Comment by ilblackdragon** [comment] 2020-07-25 19:14
Here is a draft of such BatchAccount:

```
class BatchAccount {
    constructor(connection, accountId) {
        this.connection = connection;
        this.accountId = accountId;
        this.keys = null;
    }

    async fetchKeys() {
        const keys = [];
        let i = 0;
        while (i < MAX_KEYS) {
            try {
                const publicKey = await this.connection.signer.getPublicKey(this.accountId, `${this.connection.networkId}${i}`);
                keys.push({ publicKey });
            } catch (error) {
                break;
            }
        }
        keys.forEach(async (x) => {
            x.accessKey = await this.connection.provider.query(`access_key/${this.accountId}/${x.publicKey.toString()}`);
        });
        console.log(`Found ${keys.length} keys for ${this.accountId}`)
        return keys;
    }

    async batchSendTransactions(transactions) {
        if (this.keys === null) {
            this.keys = await this.fetchKeys();
        }
        let status = await this.connection.provider.status();
        let blockHash = nearAPI.utils.serialize.base_decode(status.sync_info.latest_block_hash);
        let prepared = [];
        let txHashes = [];s
        for (let i = 0; i < transactions.length; ++i) {
            let keyId = i % this.keys.length;
            let key = this.keys[keyId];
            let networkId = `${this.connection.networkId}${keyId}`;
            let [txHash, signedTx] = nearAPI.transactions.signTransaction(
                this.accountId, key.publicKey, transactions[i].receiverId, ++key.nonce, transactions[i].actions, blockHash, this.connection.signer, this.accountId, networkId
            );
            let bytes = signedTx.encode();
            prepared.push(Buffer.from(bytes).toString('base64'));
            txHashes.push({ txHash, receiverId: transactions[i].receiverId });
        }
        let promises = prepared.map((bytes) => {
            return this.connection.provider.sendJsonRpc('broadcast_tx_async', [bytes])
        });
        await Promise.all(promises);
       // TODO: fetch results of all the transactions. Possibly resending them.
    }
}
```

**Comment by janedegtiareva** [comment] 2020-07-29 17:49
This needs re-estimating. It's definitely higher than a 3

**Comment by janedegtiareva** [comment] 2020-07-29 18:17
Does it make sense to add this functionality to all accounts instead of batch accounts? I think it may be able to help with app responsiveness for a single end-user account as well. (e.g. message app where a user quickly sent 3 different messages)

**Comment by janedegtiareva** [comment] 2020-08-03 21:36
API for keystores will need to be reworked, unless we go with the account namespacing suggestion. (current API is like this 

``` abstract async setKey(networkId: string, accountId: string, keyPair: KeyPair): Promise<void>;
    abstract async getKey(networkId: string, accountId: string): Promise<KeyPair>;```

**Comment by evgenykuzyakov** [comment] 2020-08-03 21:36
How an application will acquire multiple access keys in the first place?
@vgrichina has a PR for caching nonce locally, so it allows sending multiple transactions in parallel. The issue is RPC routing that might send them in invalid order and some of them are processed before smaller nonce TXs reaching out the mempool


Long-term solution should be to replace incremental nonces with random nonces.

**Comment by janedegtiareva** [comment] 2020-08-03 22:07
Dropping priority to P2 since most of the pain points are addressed in https://github.com/near/near-api-js/pull/374

**Closed** 2022-07-14 20:39 UTC
Labels: enhancement, P1, blocked
