### ISSUE TITLE
Passkeys/webauthn popup not triggering in Chrome

### ISSUE THREAD

**Issue by alenNBH** [near/near-api-js#1335] opened 2024-04-08 18:08 UTC
### Prerequisites

- [X] I'm using the latest version of `near-api-js`.
- [X] I have tried to start with a fresh project and reproduce the defect with minimal code changes.
- [X] I have read the console error messages carefully (if applicable).

### Description

During the setup of FastAuth after complete configuration when landing on the Cloud Run application URL from received sign email during registration, the passkey/webauthn popup doesn't show in Chrome. It works in Safari.

### Steps to reproduce

1. Follow the documentation for FastAuth: https://docs.near.org/tools/fastauth-sdk
2. Create a minimal reproducible frontend application.
3. Trigger registration of user on testnet.
4. Receive signin email.
5. Click on the link.
6. Wait for timeout (there is no prompt for creating passkey)sign in

### Expected behavior

Show passkey popup for creating passkey for user
![Screenshot 2024-04-08 at 20 04 49](https://github.com/near/near-api-js/assets/123950803/ff5badd7-805e-49fb-9039-c66afa6508f4)

### Actual behavior

Timing out without any errors or logs
![Screenshot 2024-04-08 at 20 05 07](https://github.com/near/near-api-js/assets/123950803/170a8d2e-c396-42ad-825b-412ed99c4d13)

### Your environment

- NEAR JavaScript API version used:
- Frontend framework (if applicable): React
- Relevant dependencies (if applicable): 
Chrome Version 123.0.6312.107 (Official Build) (x86_64)
![Screenshot 2024-04-08 at 20 02 10](https://github.com/near/near-api-js/assets/123950803/0311aec2-7b76-486a-8339-99889a23f7ba)

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by hcho112** [comment] 2024-04-08 23:46
@alenNBH thank you for your report. 
First of all, is it possible if you could push your project to github and share in here? (this may speed up the process)

Otherwise, would I be able to get more info on your environment?
1. What OS are you using? (more specific, better it is)
2. Are you using any password manager? (1Password, Lastpass etc) If so, which one are you using?
3. Have you tried on Chrome Cognito? (with all extensions off)
4. Any meaningful error message on developer console? (would you be able to repeat and share the screenshot?) 

Once I get these details, I can do a further investigation.

**Comment by alenNBH** [comment] 2024-04-09 10:03
Hi @hcho112,

I can actually recreate the issue by going directly to signer app that is on this link: [https://fast-auth-sdk-frontend-xbgueyzluq-uc.a.run.app/create-account](url)
After I fill the registration form and receive the sign in email, I open the link in email and it times out after that. 

1. 
![Screenshot 2024-04-09 at 11 58 12](https://github.com/near/near-api-js/assets/123950803/01f3a6b2-803e-4f4f-82d4-5d97ccbf3f36)
2. No
3. Yes, I can reproduce it in incognito as well
4. This are the only logs in the console:
![Screenshot 2024-04-09 at 11 59 11](https://github.com/near/near-api-js/assets/123950803/9acaf692-f4b9-4230-80e6-d513dff1ea0b)

**Comment by hcho112** [comment] 2024-04-10 04:27
<img width="2123" alt="image" src="https://github.com/near/near-api-js/assets/6027014/a2f90bba-f92a-4223-b95b-22392c535ee9">
I'm using M1 mac with chrome to replicate above issue. (I don't have a machine that matches exact above sepc) But I got error on /new_account endpoint with error 401 Unauthorized. (can you also confirm that you got status 200 for this endpoint?)

**Comment by alenNBH** [comment] 2024-04-10 09:08
On which page/URL and step are you getting that? I don't see that endpoint when trying to get the passkey popup to show on Chrome or Safari.

**Comment by hcho112** [comment] 2024-04-11 21:41
I was using [https://fast-auth-sdk-frontend-xbgueyzluq-uc.a.run.app/create-account](https://github.com/near/near-api-js/issues/url) and attempt to create an account

**Comment by alenNBH** [comment] 2024-04-12 08:08
For MPC recovery I'm still waiting for a ticket to be resolved here: https://github.com/near/mpc-recovery/issues/563
On my side, in Chrome, I don't even get to that point where it pings /new_account endpoint. 
To be fair it gets to that step when going through Safari but it doesn't get to it on Chrome.
I will update the OS today and try to record a video of the process so that I can show it to you.

**Comment by vikinatora** [comment] 2024-04-15 11:16
I just tried using the url @alenNBH [provided](https://fast-auth-sdk-frontend-xbgueyzluq-uc.a.run.app/create-account) and it didn't work out. In my opinion something is wrong with the source code as my MacBook M2 doesn't have issues creating biometric key pairs.

**Comment by alenNBH** [comment] 2024-04-15 18:01
Hi all,
I have now tried to recreate the issue with the updated OS version and it finally showed me the popup for the passkey in Chrome. 
The only thing is that I guess it works only with the latest version of OS...

**Comment by hcho112** [comment] 2024-04-16 02:05
@alenNBH Glad to hear. The adoption of passkey is actually fairly recent so it make sense that updating OS fixed the problem. Since this is no longer problem with passkey, we can consider this issue has been resolved?

**Comment by vikinatora** [comment] 2024-04-16 06:02
I agree that we can close the issue, even if there's some problem, I don't believe it's near-api-js the root cause

**Closed by vikinatora** 2024-04-16 06:02 UTC
Labels: bug
