### ISSUE TITLE
ES6 import fails

### ISSUE THREAD

**Issue by vans163** [near/near-api-js#607] opened 2021-05-25 22:34 UTC
near-cli uses this package but with require.

On a platform with no require. (but ES6 import)

Using it with import leads to a slew of issues (for use in a regular JS app without browser).

**Comment by vuhg** [comment] 2021-05-28 09:38
Same with #593, can't work with https://vitejs.dev/, which uses esbuild.

We should prioritize es6 module in 2021!

**Comment by vans163** [comment] 2021-06-07 22:30
Any timeline on this, this is a blocker for us to do some interesting stuff.

**Comment by volovyk-s** [comment] 2021-06-10 13:07
Let's continue the discussion in this issue: https://github.com/near/near-api-js/issues/593
@vans163 @vuhg you can submit PR's, but please, check https://github.com/near/near-api-js/pull/598 first.

**Comment by vans163** [comment] 2021-06-12 16:30
It seems these 2 issues are unrelated to this next question but I was wondering if its possible to get the ES6 version of this library to work similar to near-cli, so transactions can be signed+submitted to mainnet if fed a seedphrase/privatekey in a non-browser app.

**Comment by volovyk-s** [comment] 2021-06-15 08:16
@MaximusHaximus , we need some help from a JS person here :) Is it something that we can fix and how?

**Comment by MaximusHaximus** [comment] 2021-07-08 05:14
@volovyk-s Yes, we can publish an both an esm module version and the currently commonjs version.

We'd keep publishing the standard JS version to `/lib/`, and leave `main` in `package.json` set to `lib/index.js`.
However, we'd then also publish the ESM version to `/esm/` also -- it just takes running `tsc` with a different config json file that targets `esnext` for the module IIRC.

I *think* that should be all we need to do :). Anyone wanting to import ESM modules would just import from `near-api-js/esm` :)

Check out this handy-dandy example changset from the Sentry repo where they added an ESM build to their existing pipeline:
https://github.com/getsentry/sentry-javascript/pull/1779/files

Also related to 'new shiny import capabilities', It's also worth reading about package.json `exports` keyword usage: https://2ality.com/2021/06/typescript-esm-nodejs.html#package-exports%3A-hiding-package-internals-and-providing-nicer-module-specifiers

**Comment by vans163** [comment] 2021-09-26 10:22
Any status update on this, it would be nice to be able to use near-api-js from serverless environments (AWS/cloudflare) to do things like call contracts.

**Comment by volovyk-s** [comment] 2021-09-30 13:56
@vans163 I will try to work on it this month. If it's urgent - please, create a PR.

**Comment by vans163** [comment] 2021-09-30 21:31
> @vans163 I will try to work on it this month. If it's urgent - please, create a PR.

Not urgent. Thanks.

**Comment by tonborzenko** [comment] 2021-11-20 23:57
Hello guys, thats critical bug for me, I don't know how to add near-api-js to my application. I tried _@originjs/vite-plugin-commonjs_, but it doesn't work. Then I tried to add in packages.json your branch **#esm-artifacts**, and `import nearAPI from 'near-api-js/esm'`, but it doesn't work too. Can you make it work?

**Comment by volovyk-s** [comment] 2021-11-22 13:51
@tonborzenko please, use import without the `/esm` suffix.
I have deleted import limitations, please, try again.

**Comment by vans163** [comment] 2022-01-31 21:14
I got this to work with CJS with some fixes. This only supports webpack and you need 

webpack.config.js
```
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    }),
    new webpack.DefinePlugin({
      'process.env.NEAR_NO_LOGS': true,
    })
```
Buffer and process plugins.

I think this line needs revising because this also crashes inside browsers with `process is not defined` if we build without using webpack+that plugin. https://github.com/near/near-api-js/blob/fd6d643dd9f0d4815a5f14b0525750e86433c862/src/account.ts#L161

Perhaps check here first is `process !== undefined`. This will break ESM. I suggest using `globalThis` instead of process. That way it is generic to all environments.

**Comment by Omhet** [comment] 2022-04-24 18:24
Having the same problem with import in Vite project

**Comment by VolanDeVovan** [comment] 2022-05-07 20:36
Created a repository which you can use as an example until its fixed
https://github.com/VolanDeVovan/near-vite-example

**Comment by punithbm** [comment] 2022-10-14 12:03
> Created a repository which you can use as an example until its fixed https://github.com/VolanDeVovan/near-vite-example

@VolanDeVovan  Example you've created is outdated now. If possible can you update it with latest changes ?

**Comment by KartikSoneji** [comment] 2022-11-14 20:02
Adding a an alias to the unminified file seems to work

`vite.config.js`
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  resolve: {
    alias: {
      "near-api-js": "near-api-js/dist/near-api-js.js"
    }
  }
})
```

**Comment by TMadzi** [comment] 2022-11-16 11:21
I found a fix that fixed the Buffer error for me.

[](https://github.com/vitejs/vite/discussions/2785)

```
npm add node-stdlib-browser
npm add -D vite-plugin-node-stdlib-browser
```

// vite.config.js

```
import { defineConfig } from 'vite'
import nodePolyfills from 'vite-plugin-node-stdlib-browser'
export default defineConfig({
  // other options
  plugins: [nodePolyfills()]
})
```

Hope this helps

**Comment by jessupjn** [comment] 2023-02-10 21:02
Gentle ping on this - adding `'near-api-js': 'near-api-js/dist/near-api-js.js'` doesn't work for me because libraries we depend on import from `near-api-js/lib` as well

**Comment by jessupjn** [comment] 2023-02-10 22:46
I've done some work to resolve the outstanding issues on my end to allow for the `near-api-js` alias - but now it seems that I am getting an issue from within the `@near-wallet-selector` lib indicating an issue with `import { providers } from "near-api-js";` returning undefined... 
```
TypeError: Cannot read properties of undefined (reading 'JsonRpcProvider')
    at new Provider$1 (index-d11dc668.js:1125:12875)
    at index-d11dc668.js:1125:89530
    at Generator.next (<anonymous>)
    at Ze (index-d11dc668.js:1125:12617)
```

**Comment by andy-haynes** [comment] 2023-02-23 19:14
Hi @jessupjn, I actually have a PR to address this. It's currently in the review phase and is part of the upcoming refactor which will break up `near-api-js` functionality into separate packages.

https://github.com/near/near-api-js/pull/1067

Please feel free to take a look and leave any feedback or questions you might have. There is an `example-vite` project in the PR with a working example of ESM imports. You might also have luck linking the packages locally to verify that it works with the new packages, but I have not tried this yet.

**Comment by jessupjn** [comment] 2023-02-24 14:30
Great - I'll give it a whirl when I find some time! Is there an ETA on this PR going out?

**Comment by andy-haynes** [comment] 2023-03-01 21:22
> Great - I'll give it a whirl when I find some time! Is there an ETA on this PR going out?

@jessupjn  I'm optimistic that we can have it published by the end of March, we should have much better availability coming up.

If you have more questions about this work I'd strongly encourage you to leave comments on that PR or on #1056, which is a prerequisite. The more discussion and questions going on there will help drive home the point of how important these improvements are and hopefully get it out to developers sooner 😄

**Comment by kujtimprenkuSQA** [comment] 2023-03-03 10:06
> I've done some work to resolve the outstanding issues on my end to allow for the `near-api-js` alias - but now it seems that I am getting an issue from within the `@near-wallet-selector` lib indicating an issue with `import { providers } from "near-api-js";` returning undefined...

@jessupjn can you please check this comment https://github.com/near/near-api-js/issues/1072#issuecomment-1452468681 you might be able to resolve the issues with `Vite` + `near-api-js` + `wallet-selector`.

Follow the links on that comment for better understanding.

**Comment by ghimire007** [comment] 2023-06-27 07:33
The issue is fixed now as large near-api-js was broken down into multiple number of smaller packages as  (@near-js/*) . You can find the packages at https://www.npmjs.com/search?q=%40near-js  and use es6 imports as:

```
import {BrowserLocalStorageKeyStore  } from '@near-js/accounts'
import {ConnectedWalletAccount  } from '@near-js/wallet-account'
```

**Closed** 2023-06-28 12:24 UTC
Labels: bug, dependencies, P1, devx, help_wanted
