### ISSUE TITLE
CreateAccount and DeployContract can be more robust if use broadcast-txn-async

### ISSUE THREAD

**Issue by ailisp** [near/near-api-js#360] opened 2020-07-20 23:42 UTC
Like this fail: https://buildkite.com/nearprotocol/rainbow-bridge/builds/373#5eed625f-630c-4677-9d66-92bb5b32cf43
Error was createAccount rpc timeout, but when you retry, the previous createAccount become success, thus lead to "AccountAlreadyExist". I work around it there, but it probably considers to be a bug in near-api-js. Currently near-api-js did broadcast-txn-commit then poll tx-status. broadcast-txn-commit sometimes timeout and failed to returns the txHash, but the txn was actually successfully submitted. A more reliable way would be use broadcast-txn-async and poll tx-status until success/fail. The benefit is:
- it's not much different to turn broadcast-txn-commit+poll tx-status into broadcast-txn-async+poll
- broadcast-txn-async almost never timeout, make submit txn reliable

 /cc @vgrichina

**Comment by janedegtiareva** [comment] 2020-07-22 21:54
Draft PR https://github.com/near/near-api-js/pull/370

**Comment by janedegtiareva** [comment] 2020-07-22 22:30
- broadcast_tx_async result only contains txn hash
- broadcast_tx_commit gives a json object that includes receipts, etc
- doing this will require major changes to signAndSendTransaction in account.ts and a few functions in json-rpc-provider.ts, so adding test coverage for txn error cases is important before doing this
- this has high devx value to make the apis more robust

**Comment by vgrichina** [comment] 2020-07-23 23:22
@ailisp @janedegtiareva  AFAIK there is change (https://github.com/nearprotocol/nearcore/issues/2867) from @bowenwang1996 to make `broadcast_tx_commit` succeed when you send same transaction second time. 

So either that change isn't real or the problem is with something else.

Changing to use `broadcast_tx_async` + comes with it's own set of problems, I'd prefer we don't do it.

**Comment by ailisp** [comment] 2020-07-23 23:33
@vgrichina we encountered a tricky case with broadcast_tx_commit in bridge:
- check account exist: get "not exist"
- send create account first time (fail, timeout)
- call createAccount for second time, fail, get account exists (turn out to be first time was success)

> broadcast_tx_commit succeed when you send same transaction second time.

We should do resend until success before return createAccount method, otherwise it timeout and user call createAccount second time encounter account already exist

> Changing to use broadcast_tx_async + comes with it's own set of problems, I'd prefer we don't do it.

Benefit of broadcast_tx_async is it almost never timeout, and combine it with poll txStatus before return createAccount gives user same "createAccount Sync" effect. What is the problem of it?

**Comment by bowenwang1996** [comment] 2020-07-24 00:49
@vgrichina is it possible that retry wait is not long enough?

**Comment by janedegtiareva** [comment] 2020-08-03 21:41
This is very likely fixed by https://github.com/near/near-api-js/pull/374

**Closed by janedegtiareva** 2020-08-03 21:41 UTC
Labels: P1, bug
