### ISSUE TITLE
functionCall arguments formated in Json only

### ISSUE THREAD

**Issue by stefan-b10** [near/near-api-js#1213] opened 2023-12-01 08:12 UTC
### Description

I am trying to call a method (`deploy_code`) on a smart contract (aurora) deployed on Near. 
Based on docs : https://github.com/aurora-is-near/aurora-contracts-sdk/blob/main/docs/AuroraFromNear.md
the method takes as input the raw EVM bytecode. The issue is that near-api-js formats the arguments in Json format and there is no way of creating a `functionCall` with the argument as the raw EVM bytecode of the smart contract that will be deployed on Aurora (I might missunderstood and might be wrong)
@pivortex @Karkunow

**Comment by PiVortex** [comment] 2023-12-01 16:04
My understanding is that you want to interact with an Aurora smart contract from a NEAR smart contract.

You are using near-api-js, which is used to interact with the chain offchain.
When writing smart contract in js you use [near-sdk-js](https://docs.near.org/sdk/js/introduction)

To interact from contract to contract you need to use a [cross contract call](https://docs.near.org/develop/contracts/crosscontract#:~:text=Cross%2Dcontract%20calls%20work%20by,contract%20with%20the%20result%20(%20Promise.)




![image](https://github.com/near/near-api-js/assets/124691791/dac14655-db26-442f-9285-921cb92001c3)

**Comment by stefan-b10** [comment] 2023-12-01 16:37
I want to intreact with Aurora smart contract from a Near account (not from a smart contract)

**Comment by Karkunow** [comment] 2023-12-01 17:06
Here is an example.
https://testnet.nearblocks.io/txns/BXXkEMBBomKrGL4PSghtgvPmzukc9sKDzB5Mr2etfxuw#execution
Deploys a simple contract with a 256-bit counter. You can see the argument to deploy_code is exactly the EVM bytecode used to deploy the contract:
```608060405234801561000f575f80fd5b506101448061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c806313bdfacd14610038578063371303c014610056575b5f80fd5b610040610060565b60405161004d9190610095565b60405180910390f35b61005e610068565b005b5f8054905090565b60015f5461007691906100db565b5f81905550565b5f819050919050565b61008f8161007d565b82525050565b5f6020820190506100a85f830184610086565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6100e58261007d565b91506100f08361007d565b9250828201905080821115610108576101076100ae565b5b9291505056fea2646970667358221220f45bb480146b501c623aa53ee4dc5aca4a2729317ecb9a45c768185160c1284064736f6c63430008160033```

**Comment by Karkunow** [comment] 2023-12-01 17:07
Note the return value is a borsh-encoded struct containing information about the execution (logs, gas used, return value, etc). The definition of this struct is here (https://github.com/aurora-is-near/aurora-engine/blob/develop/engine-types/src/parameters/engine.rs#L232).
The return value included in the SubmitResult contains the address where the contract was deployed. In my case it was deployed to 0x202ef3618820deadca5017cc585d489c585cc2e3.
The contract has two methods: print() and inc(), which return the current value of the counter and increment it by 1, respectively.
You can see I call inc() in https://testnet.nearblocks.io/txns/DqrGbWFZTXFsGoLowXXiyXzBCtNEom76LymD6nZMqrj4#execution
In that transaction, the argument is a borsh-encoded struct that says what contract to call and what input to pass. The definition of that struct is here (https://github.com/aurora-is-near/aurora-engine/blob/develop/engine-types/src/parameters/engine.rs#L277). The return value is a SubmitResult, same as for deploy_code.
Here is a transaction where I call print. This is only for illustration purposes -- since this function does not cause any state change it should be done as a view call instead of an actual transaction. https://testnet.nearblocks.io/txns/DGDu9B4kjoMbx3iSTRD2R4WUyajDH8V4AsLEcfxZCPt6#execution
You can see the value contained in the SubmitResult returned from the call is 0x0000000000000000000000000000000000000000000000000000000000000001 because I called inc one time before the print

**Comment by Karkunow** [comment] 2023-12-01 17:07
Here is source code of the Counter contract:
```// SPDX-License-Identifier: MIT
pragma solidity >=0.6.12 <0.9.0;

contract Counter {
  uint256 value;

  function print() public view returns (uint256) {
    return value;
  }

  function inc() public {
    value = value + 1;
  }
}```

**Comment by PiVortex** [comment] 2023-12-01 17:38
Thank you @Karkunow 
I should have clarified, though. An example of the actual call  (to deploy) that is being made would be good (in near-api-js or whatever it is using to make the call)

**Comment by Karkunow** [comment] 2023-12-01 19:41
@PiVortex @stefan-b10 
Here is an example of call from `near-cli`:
```near call aurora aurora deploy_code --accountId ikaurora.testnet --base64 --args 608060405234801561000f575f80fd5b506101448061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610034575f3560e01c806313bdfacd14610038578063371303c014610056575b5f80fd5b610040610060565b60405161004d9190610095565b60405180910390f35b61005e610068565b005b5f8054905090565b60015f5461007691906100db565b5f81905550565b5f819050919050565b61008f8161007d565b82525050565b5f6020820190506100a85f830184610086565b92915050565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b5f6100e58261007d565b91506100f08361007d565b9250828201905080821115610108576101076100ae565b5b9291505056fea2646970667358221220f45bb480146b501c623aa53ee4dc5aca4a2729317ecb9a45c768185160c1284064736f6c63430008160033```

@PiVortex, as you can see it has an option of `--base64 --args`.

**Comment by Karkunow** [comment] 2023-12-01 19:57
Sorry, just checked the transactions and they are all failing, because base64 is ruining the HEX Bytecode from EVM there.
And we just need to pass it as `args` to the contract method.
So we actually require `raw` args format to be accesible.

**Comment by Karkunow** [comment] 2023-12-01 20:01
Ok, I've figured it our finally, just needed to re-encode bytecode into `base64` format.
The correct CLI command is:
```
near call aurora deploy_code --accountId ikaurora.testnet --base64 --args YIBgQFI0gBVhAA9XX4D9W1BhAUSAYQAdXzlf8/5ggGBAUjSAFWEAD1dfgP1bUGAENhBhADRXXzVg4ByAYxO9+s0UYQA4V4BjNxMDwBRhAFZXW1+A/VthAEBhAGBWW2BAUWEATZGQYQCVVltgQFGAkQOQ81thAF5hAGhWWwBbX4BUkFCQVltgAV9UYQB2kZBhANtWW1+BkFVQVltfgZBQkZBQVlthAI+BYQB9VluCUlBQVltfYCCCAZBQYQCoX4MBhGEAhlZbkpFQUFZbf05Ie3EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAX1JgEWAEUmAkX/1bX2EA5YJhAH1WW5FQYQDwg2EAfVZbklCCggGQUICCERVhAQhXYQEHYQCuVltbkpFQUFb+omRpcGZzWCISIPRbtIAUa1AcYjqlPuTcWspKJykxfsuaRcdoGFFgwShAZHNvbGNDAAgWADM=```

I get the positive result from it :) 
Here is the tx:
https://explorer.testnet.near.org/transactions/Em3MsBtXdznLsCokyFEcAs67Ke3a5xZp5nWqnfwAy7wo

**Comment by Karkunow** [comment] 2023-12-02 01:25
Here is a bit more explanation of what we need (or @stefan-b10 needs).
We have a contract module in `near-api-js` which uses `near-abi` module.
And the problem is that it uses only JSON encoded args.
But we want him to be able to also encode them in Base64 or Borsch:
https://github.com/near/near-abi-js/blob/main/src/index.ts#L93

**Comment by Karkunow** [comment] 2023-12-02 01:27
Hm, I realised that Borsh serialization is not correct or good enough, because the schema still enforces us to have an `argname` and we do not want to have the argument names at all. 
We just want to encode them into one big base64 or borsh chunk and send with a `call` to contract.

**Comment by PiVortex** [comment] 2023-12-02 12:41
Possible to encode EVM bytecode as args_base64 and use RPC? https://docs.near.org/api/rpc/contracts#call-a-contract-function

**Comment by stefan-b10** [comment] 2023-12-02 12:50
> Possible to encode EVM bytecode as args_base64 and use RPC? https://docs.near.org/api/rpc/contracts#call-a-contract-function

This is for calling a contract function only as ``view``

**Comment by Karkunow** [comment] 2023-12-03 02:54
@PiVortex, yeah, do you know how we can call it with "execution"? :) 
I guess the caller key should be attached to it in this case.

**Comment by frol** [comment] 2023-12-03 20:42
@Karkunow You were very close, you could have just looked up near-cli source code and find how it uses near-api-js:

https://github.com/near/near-cli/blob/148d8eae7f4f4f9326825f1e2bf21b21f52783ef/commands/call.js#L53-L63

**Comment by Karkunow** [comment] 2023-12-05 17:24
@frol, oh great, thanks! :)
@stefan-b10, does it make it clear for you?

**Comment by PiVortex** [comment] 2023-12-07 10:18
@stefan-b10 you wanted to use RPC directly or near-api-js?

Here is the docs for borsh serializing in javascript https://github.com/near/borsh-js
I believe this is also base 64

**Comment by Karkunow** [comment] 2023-12-15 12:53
@stefan-b10 have you resolved your issues?

**Comment by stefan-b10** [comment] 2023-12-15 12:55
> @stefan-b10 have you resolved your issues?

Not yet. Cannot figure out how to Borsh serialize the argumest. Transaction result a error  `"ExecutionError": "Smart contract panicked: ERR_BORSH_DESERIALIZE" `

**Comment by PiVortex** [comment] 2023-12-15 13:13
@stefan-b10 did you try serializing like in this example?
https://github.com/near/borsh-js?tab=readme-ov-file#examples

**Comment by stefan-b10** [comment] 2023-12-15 13:20
> @stefan-b10 did you try serializing like in this example? https://github.com/near/borsh-js?tab=readme-ov-file#examples

Have tried a few ways but with no success. For `FunctionCallArgsV2` shouldn`t this be the schema?
```
const schema = {
    struct: {
      contract: "string",
      input: { array: { type: "u8" } },
    },
  };
```

**Comment by stefan-b10** [comment] 2023-12-15 16:29
@frol can you please help me figure out how it should be serialized?

**Comment by PiVortex** [comment] 2023-12-15 18:19
@stefan-b10 where are you seeing the definition for V1? Have you tried adding the value for FunctionCallArgsV2 given by
```
#[derive(BorshSerialize, BorshDeserialize, Debug, PartialEq, Eq, Clone)]
pub struct FunctionCallArgsV2 {
    pub contract: Address,
    /// Wei compatible Borsh-encoded value field to attach an ETH balance to the transaction
    pub value: WeiU256,
    pub input: Vec<u8>,
}
```

**Comment by stefan-b10** [comment] 2023-12-15 18:25
> @stefan-b10 where are you seeing the definition for V1? Have you tried adding the value for FunctionCallArgsV2 given by
> 
> ```
> #[derive(BorshSerialize, BorshDeserialize, Debug, PartialEq, Eq, Clone)]
> pub struct FunctionCallArgsV2 {
>     pub contract: Address,
>     /// Wei compatible Borsh-encoded value field to attach an ETH balance to the transaction
>     pub value: WeiU256,
>     pub input: Vec<u8>,
> }
> ```

Here you can find `FunctionCallArgsV1`
https://github.com/aurora-is-near/aurora-engine/blob/develop/engine-types/src/parameters/engine.rs#L277
Was trying to call just a view function, but I have tried with `FunctionCallArgsV2` as well and got the same result

**Comment by frol** [comment] 2023-12-19 18:26
@stefan-b10 Please, create a [StackOverflow question with `nearprotocol` tag](https://stackoverflow.com/questions/tagged/nearprotocol) with a clear minimum reproducible example and your expectations communicated there. The original issue is resolved as far as I can tell (please, close it), and the next question is not clear which makes it hard to help you.

**Comment by Karkunow** [comment] 2023-12-20 01:05
@stefan-b10, maybe try doing an issue in the `[borsh-js](https://github.com/near/borsh-js)` repo?

**Closed** 2023-12-20 11:39 UTC
