### ISSUE TITLE
Local storage entry contains "undefined" and seem to contain limited list in "allKeys"

### ISSUE THREAD

**Issue by mikedotexe** [near/near-api-js#380] opened 2020-08-04 23:28 UTC
**Describe the bug**
I'm not sure of the behavioral impact, but I noticed that there was a difference between what near cli returns after:
`near keys oracle-client.testnet`

and what appeared in the Local Storage in my browser's developer tools.

**To Reproduce**
1. Go to https://gitpod.io/#https://github.com/near-examples/wallet-example
2. Proceed as normally, log in
3. Open developer tools, to go Applications, open up Local Storage on the left sidebar
4. See this odd behavior:

<img width="1431" alt="Screenshot 2020-08-04 16 24 20" src="https://user-images.githubusercontent.com/1042667/89355072-58568300-d66f-11ea-97e3-630bccaad25a.png">

Tagging Vlad as you possibly have the most context on the Wallet » dApp interaction and have done recent work on this repo.

**Comment by vgrichina** [comment] 2020-08-06 09:24
@mikedotexe `allKeys` represents all keys available to wallet for signing. Not all full access keys are available (e.g. recovery keys or near-shell keys aren't).

**Comment by mehtaphysical** [comment] 2021-04-21 15:24
To fix the undefined we need to create some default for `appKeyPrefix` here: https://github.com/near/near-api-js/blob/27ca6cddd12e62181fd37b72092de614788ff7c3/src/wallet-account.ts#L71

**Comment by mehtaphysical** [comment] 2021-04-23 14:28
Duplicate of #325

**Closed by mehtaphysical** 2021-04-23 14:28 UTC
Labels: P2, bug
